"""
Coach Portal DB setup — creates tables and seeds NCAA institutions.
Run once: python3 setup_coach_portal.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from dotenv import load_dotenv
load_dotenv()

from supabase_db import supa

# ── NCAA Institutions (~200 programs) ──────────────────────────────────────
NCAA_INSTITUTIONS = [
    # ── NCAA Division I ──────────────────────────────────────────────────
    {"name": "Duke University", "division": "NCAA D1", "conference": "ACC", "state": "NC", "website": "duke.edu", "email_domains": ["duke.edu"]},
    {"name": "University of Kentucky", "division": "NCAA D1", "conference": "SEC", "state": "KY", "website": "uky.edu", "email_domains": ["uky.edu", "email.uky.edu"]},
    {"name": "University of Kansas", "division": "NCAA D1", "conference": "Big 12", "state": "KS", "website": "ku.edu", "email_domains": ["ku.edu", "hawk.ku.edu"]},
    {"name": "University of Connecticut", "division": "NCAA D1", "conference": "Big East", "state": "CT", "website": "uconn.edu", "email_domains": ["uconn.edu"]},
    {"name": "Villanova University", "division": "NCAA D1", "conference": "Big East", "state": "PA", "website": "villanova.edu", "email_domains": ["villanova.edu"]},
    {"name": "Gonzaga University", "division": "NCAA D1", "conference": "WCC", "state": "WA", "website": "gonzaga.edu", "email_domains": ["gonzaga.edu"]},
    {"name": "University of North Carolina", "division": "NCAA D1", "conference": "ACC", "state": "NC", "website": "unc.edu", "email_domains": ["unc.edu", "email.unc.edu"]},
    {"name": "Michigan State University", "division": "NCAA D1", "conference": "Big Ten", "state": "MI", "website": "msu.edu", "email_domains": ["msu.edu", "broad.msu.edu"]},
    {"name": "University of Louisville", "division": "NCAA D1", "conference": "ACC", "state": "KY", "website": "louisville.edu", "email_domains": ["louisville.edu"]},
    {"name": "Western Kentucky University", "division": "NCAA D1", "conference": "CUSA", "state": "KY", "website": "wku.edu", "email_domains": ["wku.edu", "topper.wku.edu"]},
    {"name": "George Mason University", "division": "NCAA D1", "conference": "A-10", "state": "VA", "website": "gmu.edu", "email_domains": ["gmu.edu", "masonlive.gmu.edu"]},
    {"name": "Saint Mary's College of California", "division": "NCAA D1", "conference": "WCC", "state": "CA", "website": "stmarys-ca.edu", "email_domains": ["stmarys-ca.edu"]},
    {"name": "Belmont University", "division": "NCAA D1", "conference": "MVC", "state": "TN", "website": "belmont.edu", "email_domains": ["belmont.edu"]},
    {"name": "Lipscomb University", "division": "NCAA D1", "conference": "ASUN", "state": "TN", "website": "lipscomb.edu", "email_domains": ["lipscomb.edu"]},
    {"name": "Bellarmine University", "division": "NCAA D1", "conference": "ASUN", "state": "KY", "website": "bellarmine.edu", "email_domains": ["bellarmine.edu"]},
    {"name": "Liberty University", "division": "NCAA D1", "conference": "ASUN", "state": "VA", "website": "liberty.edu", "email_domains": ["liberty.edu"]},
    {"name": "Kennesaw State University", "division": "NCAA D1", "conference": "ASUN", "state": "GA", "website": "kennesaw.edu", "email_domains": ["kennesaw.edu"]},
    {"name": "Florida Gulf Coast University", "division": "NCAA D1", "conference": "ASUN", "state": "FL", "website": "fgcu.edu", "email_domains": ["fgcu.edu"]},
    {"name": "Northern Kentucky University", "division": "NCAA D1", "conference": "Horizon", "state": "KY", "website": "nku.edu", "email_domains": ["nku.edu"]},
    {"name": "Milwaukee School of Engineering", "division": "NCAA D3", "conference": "CCIW", "state": "WI", "website": "msoe.edu", "email_domains": ["msoe.edu"]},

    # ── NCAA Division II ──────────────────────────────────────────────────
    {"name": "Colorado State University-Pueblo", "division": "NCAA D2", "conference": "RMAC", "state": "CO", "website": "csupueblo.edu", "email_domains": ["csupueblo.edu"]},
    {"name": "Fort Hays State University", "division": "NCAA D2", "conference": "MIAA", "state": "KS", "website": "fhsu.edu", "email_domains": ["fhsu.edu", "mail.fhsu.edu"]},
    {"name": "Pittsburg State University", "division": "NCAA D2", "conference": "MIAA", "state": "KS", "website": "pittstate.edu", "email_domains": ["pittstate.edu", "gus.pittstate.edu"]},
    {"name": "Washburn University", "division": "NCAA D2", "conference": "MIAA", "state": "KS", "website": "washburn.edu", "email_domains": ["washburn.edu", "kc.washburn.edu"]},
    {"name": "University of Central Missouri", "division": "NCAA D2", "conference": "MIAA", "state": "MO", "website": "ucmo.edu", "email_domains": ["ucmo.edu"]},
    {"name": "Northwest Missouri State University", "division": "NCAA D2", "conference": "MIAA", "state": "MO", "website": "nwmissouri.edu", "email_domains": ["nwmissouri.edu"]},
    {"name": "Emporia State University", "division": "NCAA D2", "conference": "MIAA", "state": "KS", "website": "emporia.edu", "email_domains": ["emporia.edu"]},
    {"name": "Nebraska-Kearney", "division": "NCAA D2", "conference": "MIAA", "state": "NE", "website": "unk.edu", "email_domains": ["unk.edu", "lopers.unk.edu"]},
    {"name": "Texas A&M-Kingsville", "division": "NCAA D2", "conference": "LSC", "state": "TX", "website": "tamuk.edu", "email_domains": ["tamuk.edu"]},
    {"name": "Tarleton State University", "division": "NCAA D2", "conference": "LSC", "state": "TX", "website": "tarleton.edu", "email_domains": ["tarleton.edu"]},
    {"name": "West Texas A&M University", "division": "NCAA D2", "conference": "LSC", "state": "TX", "website": "wtamu.edu", "email_domains": ["wtamu.edu", "buffs.wtamu.edu"]},
    {"name": "Angelo State University", "division": "NCAA D2", "conference": "LSC", "state": "TX", "website": "angelo.edu", "email_domains": ["angelo.edu", "angelo.angelo.edu"]},
    {"name": "Texas Woman's University", "division": "NCAA D2", "conference": "LSC", "state": "TX", "website": "twu.edu", "email_domains": ["twu.edu", "student.twu.edu"]},
    {"name": "LeTourneau University", "division": "NCAA D3", "conference": "ASC", "state": "TX", "website": "letu.edu", "email_domains": ["letu.edu"]},
    {"name": "University of Tampa", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "ut.edu", "email_domains": ["ut.edu", "spartans.ut.edu"]},
    {"name": "Florida Southern College", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "flsouthern.edu", "email_domains": ["flsouthern.edu"]},
    {"name": "Rollins College", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "rollins.edu", "email_domains": ["rollins.edu"]},
    {"name": "Eckerd College", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "eckerd.edu", "email_domains": ["eckerd.edu"]},
    {"name": "Barry University", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "barry.edu", "email_domains": ["barry.edu", "pirates.barry.edu"]},
    {"name": "Nova Southeastern University", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "nova.edu", "email_domains": ["nova.edu", "mynsu.nova.edu"]},
    {"name": "Lynn University", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "lynn.edu", "email_domains": ["lynn.edu"]},
    {"name": "Palm Beach Atlantic University", "division": "NCAA D2", "conference": "SSC", "state": "FL", "website": "pba.edu", "email_domains": ["pba.edu"]},
    {"name": "Clayton State University", "division": "NCAA D2", "conference": "PBC", "state": "GA", "website": "clayton.edu", "email_domains": ["clayton.edu"]},
    {"name": "Shorter University", "division": "NCAA D2", "conference": "GSC", "state": "GA", "website": "shorter.edu", "email_domains": ["shorter.edu"]},
    {"name": "Young Harris College", "division": "NCAA D2", "conference": "Conf. Carolinas", "state": "GA", "website": "yhc.edu", "email_domains": ["yhc.edu"]},
    {"name": "North Georgia University", "division": "NCAA D2", "conference": "PBC", "state": "GA", "website": "ung.edu", "email_domains": ["ung.edu", "northgeorgia.edu"]},
    {"name": "Erskine College", "division": "NCAA D2", "conference": "Conf. Carolinas", "state": "SC", "website": "erskine.edu", "email_domains": ["erskine.edu"]},
    {"name": "Barton College", "division": "NCAA D2", "conference": "Conf. Carolinas", "state": "NC", "website": "barton.edu", "email_domains": ["barton.edu"]},
    {"name": "Wingate University", "division": "NCAA D2", "conference": "SAC", "state": "NC", "website": "wingate.edu", "email_domains": ["wingate.edu"]},
    {"name": "Catawba College", "division": "NCAA D2", "conference": "SAC", "state": "NC", "website": "catawba.edu", "email_domains": ["catawba.edu"]},
    {"name": "Coker University", "division": "NCAA D2", "conference": "SAC", "state": "SC", "website": "coker.edu", "email_domains": ["coker.edu"]},
    {"name": "Queens University of Charlotte", "division": "NCAA D2", "conference": "SAC", "state": "NC", "website": "queens.edu", "email_domains": ["queens.edu", "queens.queensu.ca"]},
    {"name": "Lincoln Memorial University", "division": "NCAA D2", "conference": "SAC", "state": "TN", "website": "lmunet.edu", "email_domains": ["lmunet.edu"]},
    {"name": "Tusculum University", "division": "NCAA D2", "conference": "SAC", "state": "TN", "website": "tusculum.edu", "email_domains": ["tusculum.edu"]},
    {"name": "Mars Hill University", "division": "NCAA D2", "conference": "SAC", "state": "NC", "website": "mhu.edu", "email_domains": ["mhu.edu"]},
    {"name": "Lenoir-Rhyne University", "division": "NCAA D2", "conference": "SAC", "state": "NC", "website": "lr.edu", "email_domains": ["lr.edu"]},
    {"name": "Anderson University", "division": "NCAA D2", "conference": "SAC", "state": "SC", "website": "andersonuniversity.edu", "email_domains": ["andersonuniversity.edu"]},
    {"name": "Carson-Newman University", "division": "NCAA D2", "conference": "SAC", "state": "TN", "website": "cn.edu", "email_domains": ["cn.edu"]},
    {"name": "University of West Georgia", "division": "NCAA D2", "conference": "GSC", "state": "GA", "website": "westga.edu", "email_domains": ["westga.edu"]},
    {"name": "West Alabama University", "division": "NCAA D2", "conference": "GSC", "state": "AL", "website": "uwa.edu", "email_domains": ["uwa.edu"]},
    {"name": "Christian Brothers University", "division": "NCAA D2", "conference": "GSC", "state": "TN", "website": "cbu.edu", "email_domains": ["cbu.edu"]},
    {"name": "Mississippi College", "division": "NCAA D2", "conference": "GSC", "state": "MS", "website": "mc.edu", "email_domains": ["mc.edu"]},
    {"name": "Delta State University", "division": "NCAA D2", "conference": "GSC", "state": "MS", "website": "deltastate.edu", "email_domains": ["deltastate.edu"]},
    {"name": "William Carey University", "division": "NCAA D2", "conference": "GSC", "state": "MS", "website": "wmcarey.edu", "email_domains": ["wmcarey.edu"]},
    {"name": "Spring Hill College", "division": "NCAA D2", "conference": "GSC", "state": "AL", "website": "shc.edu", "email_domains": ["shc.edu"]},
    {"name": "Belmont Abbey College", "division": "NCAA D2", "conference": "Conf. Carolinas", "state": "NC", "website": "bac.edu", "email_domains": ["bac.edu"]},
    {"name": "University of Montevallo", "division": "NCAA D2", "conference": "GSC", "state": "AL", "website": "montevallo.edu", "email_domains": ["montevallo.edu"]},
    {"name": "Trevecca Nazarene University", "division": "NCAA D2", "conference": "MEC", "state": "TN", "website": "trevecca.edu", "email_domains": ["trevecca.edu"]},
    {"name": "Lee University", "division": "NCAA D2", "conference": "MEC", "state": "TN", "website": "leeuniversity.edu", "email_domains": ["leeuniversity.edu"]},
    {"name": "Cedarville University", "division": "NCAA D2", "conference": "MEC", "state": "OH", "website": "cedarville.edu", "email_domains": ["cedarville.edu"]},
    {"name": "University of Findlay", "division": "NCAA D2", "conference": "G-MAC", "state": "OH", "website": "findlay.edu", "email_domains": ["findlay.edu"]},
    {"name": "Walsh University", "division": "NCAA D2", "conference": "G-MAC", "state": "OH", "website": "walsh.edu", "email_domains": ["walsh.edu"]},
    {"name": "Tiffin University", "division": "NCAA D2", "conference": "G-MAC", "state": "OH", "website": "tiffin.edu", "email_domains": ["tiffin.edu"]},
    {"name": "Malone University", "division": "NCAA D2", "conference": "G-MAC", "state": "OH", "website": "malone.edu", "email_domains": ["malone.edu"]},
    {"name": "Ursuline College", "division": "NCAA D2", "conference": "G-MAC", "state": "OH", "website": "ursuline.edu", "email_domains": ["ursuline.edu"]},
    {"name": "Alderson Broaddus University", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "ab.edu", "email_domains": ["ab.edu"]},
    {"name": "Concord University", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "concord.edu", "email_domains": ["concord.edu"]},
    {"name": "Davis and Elkins College", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "dewv.edu", "email_domains": ["dewv.edu"]},
    {"name": "West Virginia State University", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "wvstateu.edu", "email_domains": ["wvstateu.edu"]},
    {"name": "West Liberty University", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "westliberty.edu", "email_domains": ["westliberty.edu"]},
    {"name": "Charleston University (WV)", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "ucwv.edu", "email_domains": ["ucwv.edu"]},
    {"name": "Fairmont State University", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "fairmontstate.edu", "email_domains": ["fairmontstate.edu"]},
    {"name": "Glenville State University", "division": "NCAA D2", "conference": "MEC", "state": "WV", "website": "glenville.edu", "email_domains": ["glenville.edu"]},
    {"name": "Seton Hill University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "setonhill.edu", "email_domains": ["setonhill.edu"]},
    {"name": "California University of Pennsylvania", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "calu.edu", "email_domains": ["calu.edu"]},
    {"name": "Clarion University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "clarion.edu", "email_domains": ["clarion.edu"]},
    {"name": "Edinboro University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "edinboro.edu", "email_domains": ["edinboro.edu"]},
    {"name": "Mercyhurst University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "mercyhurst.edu", "email_domains": ["mercyhurst.edu"]},
    {"name": "Indiana University of Pennsylvania", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "iup.edu", "email_domains": ["iup.edu"]},
    {"name": "Kutztown University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "kutztown.edu", "email_domains": ["kutztown.edu"]},
    {"name": "Shippensburg University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "ship.edu", "email_domains": ["ship.edu"]},
    {"name": "Millersville University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "millersville.edu", "email_domains": ["millersville.edu"]},
    {"name": "East Stroudsburg University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "esu.edu", "email_domains": ["esu.edu"]},
    {"name": "Lock Haven University", "division": "NCAA D2", "conference": "PSAC", "state": "PA", "website": "lockhaven.edu", "email_domains": ["lockhaven.edu"]},
    {"name": "Chestnut Hill College", "division": "NCAA D2", "conference": "CACC", "state": "PA", "website": "chc.edu", "email_domains": ["chc.edu"]},
    {"name": "Post University", "division": "NCAA D2", "conference": "CACC", "state": "CT", "website": "post.edu", "email_domains": ["post.edu"]},
    {"name": "New Haven University", "division": "NCAA D2", "conference": "NE-10", "state": "CT", "website": "newhaven.edu", "email_domains": ["newhaven.edu"]},
    {"name": "Saint Anselm College", "division": "NCAA D2", "conference": "NE-10", "state": "NH", "website": "anselm.edu", "email_domains": ["anselm.edu"]},
    {"name": "American International College", "division": "NCAA D2", "conference": "NE-10", "state": "MA", "website": "aic.edu", "email_domains": ["aic.edu"]},
    {"name": "Bentley University", "division": "NCAA D2", "conference": "NE-10", "state": "MA", "website": "bentley.edu", "email_domains": ["bentley.edu"]},
    {"name": "Southern Connecticut State University", "division": "NCAA D2", "conference": "NE-10", "state": "CT", "website": "southernct.edu", "email_domains": ["southernct.edu"]},
    {"name": "Adelphi University", "division": "NCAA D2", "conference": "NE-10", "state": "NY", "website": "adelphi.edu", "email_domains": ["adelphi.edu"]},
    {"name": "Pace University", "division": "NCAA D2", "conference": "NE-10", "state": "NY", "website": "pace.edu", "email_domains": ["pace.edu"]},
    {"name": "Dominican College", "division": "NCAA D2", "conference": "CACC", "state": "NY", "website": "dc.edu", "email_domains": ["dc.edu"]},
    {"name": "Caldwell University", "division": "NCAA D2", "conference": "CACC", "state": "NJ", "website": "caldwell.edu", "email_domains": ["caldwell.edu"]},
    {"name": "Georgian Court University", "division": "NCAA D2", "conference": "CACC", "state": "NJ", "website": "georgian.edu", "email_domains": ["georgian.edu"]},
    {"name": "Holy Family University", "division": "NCAA D2", "conference": "CACC", "state": "PA", "website": "holyfamily.edu", "email_domains": ["holyfamily.edu"]},

    # ── NAIA ─────────────────────────────────────────────────────────────
    {"name": "Oklahoma Baptist University", "division": "NAIA", "conference": "Sooner Athletic", "state": "OK", "website": "okbu.edu", "email_domains": ["okbu.edu"]},
    {"name": "Bethel University (Indiana)", "division": "NAIA", "conference": "Crossroads League", "state": "IN", "website": "betheluniversity.edu", "email_domains": ["betheluniversity.edu"]},
    {"name": "Huntington University", "division": "NAIA", "conference": "Crossroads League", "state": "IN", "website": "huntington.edu", "email_domains": ["huntington.edu"]},
    {"name": "Indiana Wesleyan University", "division": "NAIA", "conference": "Crossroads League", "state": "IN", "website": "indwes.edu", "email_domains": ["indwes.edu"]},
    {"name": "Taylor University", "division": "NAIA", "conference": "Crossroads League", "state": "IN", "website": "taylor.edu", "email_domains": ["taylor.edu"]},
    {"name": "Grace College", "division": "NAIA", "conference": "Crossroads League", "state": "IN", "website": "grace.edu", "email_domains": ["grace.edu"]},
    {"name": "Marian University (Indiana)", "division": "NAIA", "conference": "Crossroads League", "state": "IN", "website": "marian.edu", "email_domains": ["marian.edu"]},
    {"name": "University of Saint Francis (Indiana)", "division": "NAIA", "conference": "Crossroads League", "state": "IN", "website": "sf.edu", "email_domains": ["sf.edu"]},
    {"name": "Spring Arbor University", "division": "NAIA", "conference": "Crossroads League", "state": "MI", "website": "arbor.edu", "email_domains": ["arbor.edu", "spring-arbor.edu"]},
    {"name": "Robert Morris University (Illinois)", "division": "NAIA", "conference": "CCAC", "state": "IL", "website": "robertmorris.edu", "email_domains": ["robertmorris.edu"]},
    {"name": "Judson University (Illinois)", "division": "NAIA", "conference": "CCAC", "state": "IL", "website": "judsonu.edu", "email_domains": ["judsonu.edu"]},
    {"name": "Olivet Nazarene University", "division": "NAIA", "conference": "CCAC", "state": "IL", "website": "olivet.edu", "email_domains": ["olivet.edu"]},
    {"name": "Trinity Christian College", "division": "NAIA", "conference": "CCAC", "state": "IL", "website": "trnty.edu", "email_domains": ["trnty.edu"]},
    {"name": "Cardinal Stritch University", "division": "NAIA", "conference": "NACC", "state": "WI", "website": "stritch.edu", "email_domains": ["stritch.edu"]},
    {"name": "Concordia University Wisconsin", "division": "NAIA", "conference": "NACC", "state": "WI", "website": "cuw.edu", "email_domains": ["cuw.edu"]},
    {"name": "Mount Mary University", "division": "NAIA", "conference": "NACC", "state": "WI", "website": "mtmary.edu", "email_domains": ["mtmary.edu"]},
    {"name": "Viterbo University", "division": "NAIA", "conference": "NACC", "state": "WI", "website": "viterbo.edu", "email_domains": ["viterbo.edu"]},
    {"name": "Freed-Hardeman University", "division": "NAIA", "conference": "MSC", "state": "TN", "website": "fhu.edu", "email_domains": ["fhu.edu"]},
    {"name": "Cumberlands University", "division": "NAIA", "conference": "MSC", "state": "KY", "website": "ucumberlands.edu", "email_domains": ["ucumberlands.edu"]},
    {"name": "Georgetown College", "division": "NAIA", "conference": "MSC", "state": "KY", "website": "georgetowncollege.edu", "email_domains": ["georgetowncollege.edu"]},
    {"name": "Tennessee Wesleyan University", "division": "NAIA", "conference": "Appalachian AC", "state": "TN", "website": "tnwesleyan.edu", "email_domains": ["tnwesleyan.edu"]},
    {"name": "Bryan College", "division": "NAIA", "conference": "Appalachian AC", "state": "TN", "website": "bryan.edu", "email_domains": ["bryan.edu"]},
    {"name": "Montreat College", "division": "NAIA", "conference": "Appalachian AC", "state": "NC", "website": "montreat.edu", "email_domains": ["montreat.edu"]},
    {"name": "Point University", "division": "NAIA", "conference": "Appalachian AC", "state": "GA", "website": "point.edu", "email_domains": ["point.edu"]},
    {"name": "Reinhardt University", "division": "NAIA", "conference": "Appalachian AC", "state": "GA", "website": "reinhardt.edu", "email_domains": ["reinhardt.edu"]},
    {"name": "Southwestern Christian University", "division": "NAIA", "conference": "Sooner Athletic", "state": "OK", "website": "swcu.edu", "email_domains": ["swcu.edu"]},
    {"name": "John Brown University", "division": "NAIA", "conference": "Sooner Athletic", "state": "AR", "website": "jbu.edu", "email_domains": ["jbu.edu"]},
    {"name": "Lyon College", "division": "NAIA", "conference": "Sooner Athletic", "state": "AR", "website": "lyon.edu", "email_domains": ["lyon.edu"]},
    {"name": "Ecclesia College", "division": "NAIA", "conference": "Sooner Athletic", "state": "AR", "website": "ecollege.edu", "email_domains": ["ecollege.edu"]},
    {"name": "Langston University", "division": "NAIA", "conference": "Red River", "state": "OK", "website": "langston.edu", "email_domains": ["langston.edu"]},
    {"name": "Bacone College", "division": "NAIA", "conference": "Red River", "state": "OK", "website": "bacone.edu", "email_domains": ["bacone.edu"]},
    {"name": "University of Science and Arts of Oklahoma", "division": "NAIA", "conference": "Sooner Athletic", "state": "OK", "website": "usao.edu", "email_domains": ["usao.edu"]},
    {"name": "Science and Technology of Oklahoma", "division": "NAIA", "conference": "Sooner Athletic", "state": "OK", "website": "opsu.edu", "email_domains": ["opsu.edu"]},
    {"name": "Wayland Baptist University", "division": "NAIA", "conference": "Red River", "state": "TX", "website": "wbu.edu", "email_domains": ["wbu.edu"]},
    {"name": "Jarvis Christian University", "division": "NAIA", "conference": "Red River", "state": "TX", "website": "jarvis.edu", "email_domains": ["jarvis.edu"]},
    {"name": "Mid-America Christian University", "division": "NAIA", "conference": "Sooner Athletic", "state": "OK", "website": "macu.edu", "email_domains": ["macu.edu"]},
    {"name": "Benedictine College", "division": "NAIA", "conference": "Heart of America", "state": "KS", "website": "benedictine.edu", "email_domains": ["benedictine.edu"]},
    {"name": "Baker University", "division": "NAIA", "conference": "Heart of America", "state": "KS", "website": "bakeru.edu", "email_domains": ["bakeru.edu"]},
    {"name": "Culver-Stockton College", "division": "NAIA", "conference": "Heart of America", "state": "MO", "website": "culver.edu", "email_domains": ["culver.edu"]},
    {"name": "Graceland University", "division": "NAIA", "conference": "Heart of America", "state": "IA", "website": "graceland.edu", "email_domains": ["graceland.edu"]},
    {"name": "MidAmerica Nazarene University", "division": "NAIA", "conference": "Heart of America", "state": "KS", "website": "mnu.edu", "email_domains": ["mnu.edu"]},
    {"name": "Missouri Valley College", "division": "NAIA", "conference": "Heart of America", "state": "MO", "website": "moval.edu", "email_domains": ["moval.edu"]},
    {"name": "Central Methodist University", "division": "NAIA", "conference": "Heart of America", "state": "MO", "website": "centralmethodist.edu", "email_domains": ["centralmethodist.edu"]},
    {"name": "Evangel University", "division": "NAIA", "conference": "Heart of America", "state": "MO", "website": "evangel.edu", "email_domains": ["evangel.edu"]},
    {"name": "Avila University", "division": "NAIA", "conference": "Heart of America", "state": "MO", "website": "avila.edu", "email_domains": ["avila.edu"]},
    {"name": "William Penn University", "division": "NAIA", "conference": "Heart of America", "state": "IA", "website": "wmpenn.edu", "email_domains": ["wmpenn.edu"]},
    {"name": "Peru State College", "division": "NAIA", "conference": "Heart of America", "state": "NE", "website": "peru.edu", "email_domains": ["peru.edu"]},
    {"name": "Dordt University", "division": "NAIA", "conference": "Great Plains", "state": "IA", "website": "dordt.edu", "email_domains": ["dordt.edu"]},
    {"name": "Northwestern College (Iowa)", "division": "NAIA", "conference": "Great Plains", "state": "IA", "website": "nwciowa.edu", "email_domains": ["nwciowa.edu"]},
    {"name": "Briar Cliff University", "division": "NAIA", "conference": "Great Plains", "state": "IA", "website": "briarcliff.edu", "email_domains": ["briarcliff.edu"]},
    {"name": "Morningside University", "division": "NAIA", "conference": "Great Plains", "state": "IA", "website": "morningside.edu", "email_domains": ["morningside.edu"]},
    {"name": "Doane University", "division": "NAIA", "conference": "Great Plains", "state": "NE", "website": "doane.edu", "email_domains": ["doane.edu"]},
    {"name": "Midland University", "division": "NAIA", "conference": "Great Plains", "state": "NE", "website": "midlandu.edu", "email_domains": ["midlandu.edu"]},
    {"name": "College of Saint Mary", "division": "NAIA", "conference": "Great Plains", "state": "NE", "website": "csm.edu", "email_domains": ["csm.edu"]},
    {"name": "Mount Marty University", "division": "NAIA", "conference": "Great Plains", "state": "SD", "website": "mountmarty.edu", "email_domains": ["mountmarty.edu"]},
    {"name": "Dakota Wesleyan University", "division": "NAIA", "conference": "Great Plains", "state": "SD", "website": "dwu.edu", "email_domains": ["dwu.edu"]},
    {"name": "Presentation College", "division": "NAIA", "conference": "Great Plains", "state": "SD", "website": "presentation.edu", "email_domains": ["presentation.edu"]},
    {"name": "Dickinson State University", "division": "NAIA", "conference": "Dakota Athletic", "state": "ND", "website": "dickinsonstate.edu", "email_domains": ["dickinsonstate.edu"]},
    {"name": "Minot State University", "division": "NAIA", "conference": "Dakota Athletic", "state": "ND", "website": "minotstateu.edu", "email_domains": ["minotstateu.edu"]},
    {"name": "Valley City State University", "division": "NAIA", "conference": "Dakota Athletic", "state": "ND", "website": "vcsu.edu", "email_domains": ["vcsu.edu"]},
    {"name": "Mayville State University", "division": "NAIA", "conference": "Dakota Athletic", "state": "ND", "website": "mayvillestate.edu", "email_domains": ["mayvillestate.edu"]},
    {"name": "University of Montana Western", "division": "NAIA", "conference": "Frontier", "state": "MT", "website": "umwestern.edu", "email_domains": ["umwestern.edu"]},
    {"name": "Carroll College", "division": "NAIA", "conference": "Frontier", "state": "MT", "website": "carroll.edu", "email_domains": ["carroll.edu"]},
    {"name": "Rocky Mountain College", "division": "NAIA", "conference": "Frontier", "state": "MT", "website": "rocky.edu", "email_domains": ["rocky.edu"]},
    {"name": "Montana State University-Northern", "division": "NAIA", "conference": "Frontier", "state": "MT", "website": "msun.edu", "email_domains": ["msun.edu"]},
    {"name": "Eastern Oregon University", "division": "NAIA", "conference": "CCC", "state": "OR", "website": "eou.edu", "email_domains": ["eou.edu"]},
    {"name": "Oregon Tech", "division": "NAIA", "conference": "CCC", "state": "OR", "website": "oit.edu", "email_domains": ["oit.edu"]},
    {"name": "Southern Oregon University", "division": "NAIA", "conference": "CCC", "state": "OR", "website": "sou.edu", "email_domains": ["sou.edu"]},
    {"name": "Corban University", "division": "NAIA", "conference": "CCC", "state": "OR", "website": "corban.edu", "email_domains": ["corban.edu"]},
    {"name": "Cascade College", "division": "NAIA", "conference": "CCC", "state": "OR", "website": "cascade.edu", "email_domains": ["cascade.edu"]},
    {"name": "Biola University", "division": "NAIA", "conference": "Golden State", "state": "CA", "website": "biola.edu", "email_domains": ["biola.edu"]},
    {"name": "The Master's University", "division": "NAIA", "conference": "Golden State", "state": "CA", "website": "masters.edu", "email_domains": ["masters.edu"]},
    {"name": "Westmont College", "division": "NAIA", "conference": "Golden State", "state": "CA", "website": "westmont.edu", "email_domains": ["westmont.edu"]},
    {"name": "Point Loma Nazarene University", "division": "NAIA", "conference": "Golden State", "state": "CA", "website": "pointloma.edu", "email_domains": ["pointloma.edu"]},
    {"name": "Menlo College", "division": "NAIA", "conference": "Golden State", "state": "CA", "website": "menlo.edu", "email_domains": ["menlo.edu"]},
    {"name": "Cal State Maritime Academy", "division": "NAIA", "conference": "Golden State", "state": "CA", "website": "csum.edu", "email_domains": ["csum.edu"]},
    {"name": "Life Pacific University", "division": "NAIA", "conference": "Golden State", "state": "CA", "website": "lifepacific.edu", "email_domains": ["lifepacific.edu"]},

    # ── JUCO / NJCAA ─────────────────────────────────────────────────────
    {"name": "Cowley County Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "cowley.edu", "email_domains": ["cowley.edu"]},
    {"name": "Hutchinson Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "hutchcc.edu", "email_domains": ["hutchcc.edu"]},
    {"name": "Barton County Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "bartonccc.edu", "email_domains": ["bartonccc.edu"]},
    {"name": "Cloud County Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "cloud.edu", "email_domains": ["cloud.edu"]},
    {"name": "Coffeyville Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "coffeyville.edu", "email_domains": ["coffeyville.edu"]},
    {"name": "Seward County Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "sccc.edu", "email_domains": ["sccc.edu"]},
    {"name": "Garden City Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "gcccks.edu", "email_domains": ["gcccks.edu"]},
    {"name": "Butler Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "butlercc.edu", "email_domains": ["butlercc.edu"]},
    {"name": "Pratt Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "prattcc.edu", "email_domains": ["prattcc.edu"]},
    {"name": "Neosho County Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "neosho.edu", "email_domains": ["neosho.edu"]},
    {"name": "Independence Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "indycc.edu", "email_domains": ["indycc.edu"]},
    {"name": "Dodge City Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "dc3.edu", "email_domains": ["dc3.edu"]},
    {"name": "Colby Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "colbycc.edu", "email_domains": ["colbycc.edu"]},
    {"name": "Allen County Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "allencc.edu", "email_domains": ["allencc.edu"]},
    {"name": "Tyler Junior College", "division": "JUCO", "conference": "ACCAC", "state": "TX", "website": "tjc.edu", "email_domains": ["tjc.edu"]},
    {"name": "Kilgore College", "division": "JUCO", "conference": "ACCAC", "state": "TX", "website": "kilgore.edu", "email_domains": ["kilgore.edu"]},
    {"name": "Lon Morris College", "division": "JUCO", "conference": "ACCAC", "state": "TX", "website": "lonmorris.edu", "email_domains": ["lonmorris.edu"]},
    {"name": "Panola College", "division": "JUCO", "conference": "ACCAC", "state": "TX", "website": "panola.edu", "email_domains": ["panola.edu"]},
    {"name": "Paris Junior College", "division": "JUCO", "conference": "ACCAC", "state": "TX", "website": "parisjc.edu", "email_domains": ["parisjc.edu"]},
    {"name": "Trinity Valley Community College", "division": "JUCO", "conference": "ACCAC", "state": "TX", "website": "tvcc.edu", "email_domains": ["tvcc.edu"]},
    {"name": "Northeast Texas Community College", "division": "JUCO", "conference": "ACCAC", "state": "TX", "website": "ntcc.edu", "email_domains": ["ntcc.edu"]},
    {"name": "Navarro College", "division": "JUCO", "conference": "NJCAA DI", "state": "TX", "website": "navarrocollege.edu", "email_domains": ["navarrocollege.edu"]},
    {"name": "Hill College", "division": "JUCO", "conference": "NJCAA DI", "state": "TX", "website": "hillcollege.edu", "email_domains": ["hillcollege.edu"]},
    {"name": "Odessa College", "division": "JUCO", "conference": "WJCAC", "state": "TX", "website": "odessa.edu", "email_domains": ["odessa.edu"]},
    {"name": "Clarendon College", "division": "JUCO", "conference": "WJCAC", "state": "TX", "website": "clarendoncollege.edu", "email_domains": ["clarendoncollege.edu"]},
    {"name": "Frank Phillips College", "division": "JUCO", "conference": "WJCAC", "state": "TX", "website": "fpctx.edu", "email_domains": ["fpctx.edu"]},
    {"name": "Ranger College", "division": "JUCO", "conference": "WJCAC", "state": "TX", "website": "rangercollege.edu", "email_domains": ["rangercollege.edu"]},
    {"name": "Western Texas College", "division": "JUCO", "conference": "WJCAC", "state": "TX", "website": "wtc.edu", "email_domains": ["wtc.edu"]},
    {"name": "South Plains College", "division": "JUCO", "conference": "WJCAC", "state": "TX", "website": "southplainscollege.edu", "email_domains": ["southplainscollege.edu"]},
    {"name": "Cisco College", "division": "JUCO", "conference": "WJCAC", "state": "TX", "website": "cisco.edu", "email_domains": ["cisco.edu"]},
    {"name": "Northeastern Oklahoma A&M College", "division": "JUCO", "conference": "ONJCAA", "state": "OK", "website": "neo.edu", "email_domains": ["neo.edu"]},
    {"name": "Murray State College", "division": "JUCO", "conference": "ONJCAA", "state": "OK", "website": "mscok.edu", "email_domains": ["mscok.edu"]},
    {"name": "Connors State College", "division": "JUCO", "conference": "ONJCAA", "state": "OK", "website": "connorsstate.edu", "email_domains": ["connorsstate.edu"]},
    {"name": "Seminole State College", "division": "JUCO", "conference": "ONJCAA", "state": "OK", "website": "sscok.edu", "email_domains": ["sscok.edu"]},
    {"name": "Eastern Oklahoma State College", "division": "JUCO", "conference": "ONJCAA", "state": "OK", "website": "eosc.edu", "email_domains": ["eosc.edu"]},
    {"name": "Carl Albert State College", "division": "JUCO", "conference": "ONJCAA", "state": "OK", "website": "carlalbert.edu", "email_domains": ["carlalbert.edu"]},
    {"name": "Mineral Area College", "division": "JUCO", "conference": "MCCAC", "state": "MO", "website": "mineralarea.edu", "email_domains": ["mineralarea.edu"]},
    {"name": "Moberly Area Community College", "division": "JUCO", "conference": "MCCAC", "state": "MO", "website": "macc.edu", "email_domains": ["macc.edu"]},
    {"name": "State Fair Community College", "division": "JUCO", "conference": "MCCAC", "state": "MO", "website": "sfccmo.edu", "email_domains": ["sfccmo.edu"]},
    {"name": "Three Rivers Community College", "division": "JUCO", "conference": "MCCAC", "state": "MO", "website": "trcc.edu", "email_domains": ["trcc.edu"]},
    {"name": "East Central College", "division": "JUCO", "conference": "MCCAC", "state": "MO", "website": "eastcentral.edu", "email_domains": ["eastcentral.edu"]},
    {"name": "Indian Hills Community College", "division": "JUCO", "conference": "ICCAC", "state": "IA", "website": "indianhills.edu", "email_domains": ["indianhills.edu"]},
    {"name": "Iowa Lakes Community College", "division": "JUCO", "conference": "ICCAC", "state": "IA", "website": "iowalakes.edu", "email_domains": ["iowalakes.edu"]},
    {"name": "Southwestern Community College", "division": "JUCO", "conference": "ICCAC", "state": "IA", "website": "swcciowa.edu", "email_domains": ["swcciowa.edu"]},
    {"name": "Southeastern Community College", "division": "JUCO", "conference": "ICCAC", "state": "IA", "website": "scciowa.edu", "email_domains": ["scciowa.edu"]},
    {"name": "Iowa Central Community College", "division": "JUCO", "conference": "ICCAC", "state": "IA", "website": "iowacentral.edu", "email_domains": ["iowacentral.edu"]},
    {"name": "North Idaho College", "division": "JUCO", "conference": "NWAC", "state": "ID", "website": "nic.edu", "email_domains": ["nic.edu"]},
    {"name": "Spokane Community College", "division": "JUCO", "conference": "NWAC", "state": "WA", "website": "scc.spokane.edu", "email_domains": ["scc.spokane.edu"]},
    {"name": "Walla Walla Community College", "division": "JUCO", "conference": "NWAC", "state": "WA", "website": "wwcc.edu", "email_domains": ["wwcc.edu"]},
    {"name": "Yakima Valley College", "division": "JUCO", "conference": "NWAC", "state": "WA", "website": "yvcc.edu", "email_domains": ["yvcc.edu"]},
    {"name": "Southwestern Oregon Community College", "division": "JUCO", "conference": "NWAC", "state": "OR", "website": "socc.edu", "email_domains": ["socc.edu"]},
    {"name": "Mt. Hood Community College", "division": "JUCO", "conference": "NWAC", "state": "OR", "website": "mhcc.edu", "email_domains": ["mhcc.edu"]},
    {"name": "Hesston College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "hesston.edu", "email_domains": ["hesston.edu"]},
    {"name": "Labette Community College", "division": "JUCO", "conference": "KJCCC", "state": "KS", "website": "labette.edu", "email_domains": ["labette.edu"]},
]


def run_setup():
    print("Setting up Coach Portal tables and data...")

    # Seed NCAA institutions
    existing = supa.table("ncaa_institutions").select("id", count="exact").execute()
    if existing.count and existing.count > 0:
        print(f"NCAA institutions already seeded ({existing.count} rows). Skipping.")
    else:
        print(f"Seeding {len(NCAA_INSTITUTIONS)} NCAA institutions...")
        # Insert in batches of 50
        for i in range(0, len(NCAA_INSTITUTIONS), 50):
            batch = NCAA_INSTITUTIONS[i:i+50]
            supa.table("ncaa_institutions").insert(batch).execute()
            print(f"  Inserted batch {i//50 + 1} ({len(batch)} institutions)")
        print("NCAA institutions seeded.")

    print("Setup complete.")


if __name__ == "__main__":
    run_setup()
